services:
  app:
    image: ghcr.io/vleerapp/api:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/vleer_api
      - SCRAPE_DATABASE_URL=postgres://postgres:postgres@localhost:5432/apple_music_scrape
      - TYPESENSE_URL=http://typesense:8108
      - TYPESENSE_API_KEY=vleer
    depends_on:
      postgres:
        condition: service_healthy
      typesense:
        condition: service_healthy
    networks:
      - vleer_api-network

  postgres:
    image: timescale/timescaledb-ha:pg17
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vleer_api
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    command: postgres -c shared_buffers=512MB -c max_connections=200 -c work_mem=16MB
    shm_size: 1g
    post_start:
      - command: chown -R 1000:1000 /var/lib/postgresql/data
        user: root
    networks:
      vleer_api-network:
        aliases:
          - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d vleer_api" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  typesense:
    image: typesense/typesense:30.1
    container_name: typesense
    restart: unless-stopped
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=vleer
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    networks:
      vleer_api-network:
        aliases:
          - typesense
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8108/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
  typesense_data:

networks:
  vleer_api-network:
    driver: bridge
